### ISSUE TITLE
Есть кто живой ?:) Вопрос по админке 

### ISSUE THREAD

**Issue by egorzot** [SibirixScrum/HelpDesk#14]
Спасибо за проект! Хоть и давний, но очень крутой !
Вопрос: на [сайте проекта](https://www.sibirix.ru/products/help-desk/) вот такие картинки красивые 
[раз](https://s.mail.ru/7GQP/xPdtqhjU9) [два](https://s.mail.ru/MpxE/Zm1AcPufj)
У администратора нету функционала, как на картинках. 
Может что-то надо в конфиге прописать?

**Comment by spChief** [comment]
Добрый день! К концу недели планируется обновление

**Comment by egorzot** [comment]
прекрасно. 
ждать плюшек как на картинках?:)

**Comment by smilingcheater** [comment]
Последние обновления выкатили, должно быть всё как на картинках :)

**Comment by shturz** [comment]
Добрый день! А кто может помочь с установкой данного сервиса?

**Comment by spChief** [comment]
@shturz Спрашивайте, если что то непонятно. Правильная настройка модуля требует знаний по администрированию серверов, конкретно - установка-настройка nodejs+mongodb. Помимо этого рекомендую В качестве фронт-сервера поставить nginx, чтобы нодой не торчать наружу.

**Comment by egorzot** [comment]
@spChief у вас есть параметры ssl в конфиге, но не совсем понятно как запустить  хедпдеск на 443 порту и настроить редирект с 80 порта на 443.
Если вставить exports.port = '443'; а в домене (параметр domain) в конфиге указать домен без порта, то при попытке создания тикета или захода в панель крашится нода:

```
123@123.123123 lxotv8kq
/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'length' of undefined
    at EventEmitter.<anonymous> (/var/www/HelpDesk/models/project.js:173:40)
    at EventEmitter.<anonymous> (/var/www/HelpDesk/node_modules/mpromise/lib/promise.js:174:48)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Promise.safeEmit (/var/www/HelpDesk/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.reject (/var/www/HelpDesk/node_modules/mpromise/lib/promise.js:109:15)
    at Promise.error (/var/www/HelpDesk/node_modules/mongoose/lib/promise.js:94:15)
    at Promise.resolve (/var/www/HelpDesk/node_modules/mongoose/lib/promise.js:112:24)
    at handleCallback (/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1587:7
    at handleCallback (/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb/lib/db.js:252:20
    at /var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:793:46
    at Callbacks.emit (/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at Connection.messageHandler (/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/var/www/HelpDesk/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:259:22)
```

Можете привести простейший пример конфига?Или если ставить nginx как прокси, может скинете ссылочку на дельную статью с примером настройки?

**Comment by egorzot** [comment]
> @spChief у вас есть параметры ssl в конфиге, но не совсем понятно как запустить хедпдеск на 443 порту и настроить редирект с 80 порта на 443.
> Если вставить exports.port = '443'; а в домене (параметр domain) в конфиге указать домен без порта, то при попытке создания тикета или захода в панель крашится нода:

Это все с включенным ssl.enabled и настроенными сертификатами.

**Comment by spChief** [comment]
@egorzot что то типа такого
```
server {
    listen   80;
    server_name helpdesk.int *.helpdesk.int;
    set         $baseDir helpdesk.int;
    include     host.conf;
    location / {
        proxy_pass          http://127.0.0.1:3000/;
        proxy_redirect      off;
        proxy_set_header    Host                $host;
        proxy_set_header    FAKE-CLIENT-IP      $remote_addr;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 128m;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
    }

}

server {
    listen 443;
    server_name helpdesk.int *.helpdesk.int;

    set         $baseDir helpdesk.int;
    include     host.conf;

    location / {
	proxy_pass          https://127.0.0.1:3000/;
        proxy_redirect      off;
	proxy_set_header    Host                $host;
        proxy_set_header    FAKE-CLIENT-IP      $remote_addr;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 128m;
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
    }

    ssl on;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_prefer_server_ciphers on;
}

```
В host.conf лежит настройка статики:
```
location ~* ^.*(images|xcache|cache|wp-content|wp-includes|wp-includes|mentant_doc|general|components|scripts|upload|bitrix|css|js)\/.+\.(png|jpg|jpeg|gif|css|ico|js|swf|mp1|mp2|mp3|zip|rar|pdf|avi|mp4|m1v|flv)$ {
    root         /var/wwwhome/$baseDir/www/;
    access_log   off;
    expires      max;
}

location ~* (favicon.ico|robots.txt) {
    root         /var/wwwhome/$baseDir/www/;
    access_log   off;
    expires      max;
}
```
