### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by Nehoko** [SibirixScrum/HelpDesk#18]
При попытке установить проект на node версий 8.10.0, 12.18.3, 14.15.3 возникает одна и та же проблема:
```gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-58-generic
gyp ERR! command "~/.nvm/versions/node/v12.18.3/bin/node" "~/.nvm/versions/node/v12.18.3/lib/node_modules
/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/Study/java_script/helpdesk/node_modules/utf-8-validate
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

Как лечить?

**Comment by spChief** [comment]
Точно работает на версии node 8.16.1
