### ISSUE TITLE
expiresInMinutes and expiresInSeconds is deprecated

### ISSUE THREAD

**Issue by kotuke** [SibirixScrum/HelpDesk#2]
При попытке оставить тикет или в дальнейшем попытке залогониться под этим пользователем получаем :boom::

```
jsonwebtoken: expiresInMinutes and expiresInSeconds is deprecated. (/home/vagrant/helpdesk/controllers/user.js:31:38)
Use "expiresIn" expressed in seconds.
/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'length' of undefined
    at EventEmitter.<anonymous> (/home/vagrant/helpdesk/models/project.js:173:39)
    at EventEmitter.<anonymous> (/home/vagrant/helpdesk/node_modules/mpromise/lib/promise.js:174:48)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Promise.safeEmit (/home/vagrant/helpdesk/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.reject (/home/vagrant/helpdesk/node_modules/mpromise/lib/promise.js:109:15)
    at Promise.error (/home/vagrant/helpdesk/node_modules/mongoose/lib/promise.js:94:15)
    at Promise.resolve (/home/vagrant/helpdesk/node_modules/mongoose/lib/promise.js:112:24)
    at handleCallback (/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1587:7
    at handleCallback (/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
    at /home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb/lib/db.js:252:20
    at /home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:793:46
    at Callbacks.emit (/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at null.messageHandler (/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/home/vagrant/helpdesk/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:259:22)
```

node.js 5.1.0
mongodb 2.0.4-1

**Comment by SibirixScrum** [comment]
Пофикшено в 0a9d978
