### ISSUE TITLE
invalid "expiresIn"

### ISSUE THREAD

**Issue by DragDG** [SibirixScrum/HelpDesk#4]
Вот такая простыня при попытке залогиниться под аккаунтом "responsible":

invalid "expiresIn" option for string payload
D:\project\helpdesk\node_modules\jsonwebtoken\index.js:109
      throw new Error('"expiresIn" should be a number of seconds or string repre
senting a timespan eg: "1d", "20h", 60');
      ^

Error: "expiresIn" should be a number of seconds or string representing a timesp
an eg: "1d", "20h", 60
    at Object.JWT.sign (D:\project\helpdesk\node_modules\jsonwebtoken\index.js:1
09:13)
    at Promise.<anonymous> (D:\project\helpdesk\controllers\user.js:31:38)
    at Promise.<anonymous> (D:\project\helpdesk\node_modules\mpromise\lib\promis
e.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (D:\project\helpdesk\node_modules\mpromise\lib\promise.js:84
:38)
    at Promise.fulfill (D:\project\helpdesk\node_modules\mpromise\lib\promise.js
:97:20)
    at D:\project\helpdesk\node_modules\mongoose\lib\query.js:1056:26
    at model.Document.init (D:\project\helpdesk\node_modules\mongoose\lib\docume
nt.js:250:11)
    at completeMany (D:\project\helpdesk\node_modules\mongoose\lib\query.js:1054
:12)

**Comment by DragDG** [comment]
ошибка вылазила из-за обновления
что бы все завелось нужно:

HelpDesk/package.json
"jsonwebtoken": "^5.0.5",
надо убрать птичку
"jsonwebtoken": "5.0.5",

и после этого в консоле "npm update"
